[project]
name = "mcp-graph-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "python-dotenv",
    "rdflib",
    "langchain>=1.2.7",
    "langchain-openai>=1.1.7",
    "langchain-mcp-adapters>=0.2.1",
    "scikit-learn>=1.8.0",
    "python-levenshtein>=0.27.3",
    "scipy>=1.15.0",
    "pynput>=1.8.1",
]
